### PR TITLE
Fix parsing of the description

### PR DESCRIPTION
**Pull request by darix**
please tag and release this as well :)

### CODE REVIEW

**Comment by M0ses** [comment]
LGTM

**Comment by darix** [comment]
anything we can help with to get this moved forward?

**Review by Firstyear — APPROVED** [review]

**Comment by Firstyear** [comment]
I wasn't sent notifications that's why I missed this.

**Comment by darix** [comment]
please tag and update the package as well :) TIA atm this missing change in the package breaks running it server side.

**Comment by Firstyear** [comment]
give me a bit please, I only just merged this and I have a long todo list today.

**Pull request merged**
