### PR TITLE
Migrate to filterer

### LINKED ISSUE #37: Reduce vendoring size
Vendoring should consider using https://github.com/coreos/cargo-vendor-filterer

This can avoid packaing many unrequired crates such as the absurd amount of Windows cruft that also includes many built binaries. Leaving these out can reduce some vendoring down to a quarter of the size.

 I changed the command to `output = run_cargo(appDirectory, "vendor-filterer", argsList + ["--platform", "x86_64-unknown-linux-gnu", "vendor"])`.

This is likely going to require either detecting the target triple, or forcing it to be passed as an arg.

### PR DESCRIPTION
**Pull request by uncomfyhalomacro**
I may have to investigate

> all-features: Enable all features of the current crate when vendoring.

after this PR. idk what that even means. 

Closes #37

### CODE REVIEW

**Comment by uncomfyhalomacro** [comment]
Alacritty be like

```
- Reduced vendored size using cargo-vendor-filterer
  * vendor.tar.xz was 28MB.. now it is 8.2MB
- Update _service file
  * replace mode "disabled" to "manual" since "disabled" is deprecated.
```

**Comment by uncomfyhalomacro** [comment]
This [build failure](https://build.opensuse.org/package/live_build_log/home:uncomfyhalomacro:branches:network:idm/kanidm/Fedora_Rawhide/x86_64) from Kanidm makes me think that `filter` should be an additional option

```xml
<services>
  <service name="cargo_vendor" mode="manual"/>
     <!-- If we want to vendor for *all* platforms even those from windows -->
     <param name="filter">*</param>
     <!-- If linux only -->
     <param name="filter">*linux*</param>
  </service>
  <service name="cargo_audit" mode="manual"/>
</services>

```

**Comment by Firstyear** [comment]
I think wrt to the configuration, it should be `<param name="filter">true|false</param>` and we default to "true". I think we don't need to expose configuration knobs to users unless there is a need to let them actually configure it, and OBS doesn't build for anything that *isn't* linux anyway today. At least not that I'm aware of!

To start with, filterer might be more reliable ifwe just exclude windows, rather than try to filter to linux specifically?

**Comment by uncomfyhalomacro** [comment]
So `filter` should be
- `true` if we want to exclude windows
- `false` if we just yolo it

It should be good i guess. need to investigate further. im not sure how or why alacritty failed so I'm going to check if doing the "yolo" makes it happy.

**Comment by uncomfyhalomacro** [comment]
@Firstyear wow... alacritty builds when i set `update` false??????

**Comment by Firstyear** [comment]
It means alacritty deps on a specific version of something, but doesn't express it properly in it's Cargo.toml. 

Anyway, I think you're right about the filter true/false thing,

**Comment by uncomfyhalomacro** [comment]
> It means alacritty deps on a specific version of something, but doesn't express it properly in it's Cargo.toml.
> 
> Anyway, I think you're right about the filter true/false thing,

Also found out. With the regular `cargo vendor` after `cargo update`:
- It builds just fine
- But big vendored tarball

With the `cargo-vendor-filterer` with filter glob `*-unknown-linux-gnu` after `cargo update`:
- Builds fail
- Disabling update is the fix?

**Comment by uncomfyhalomacro** [comment]
@Firstyear Can you please confirm it's working if you are free 🫂? For now, I will just ignore that inconsistent behavior between `cargo vendor` vs `cargo vendor-filterer`.

**Comment by uncomfyhalomacro** [comment]
Not going to merge this yet. Here are inconsistent behaviors I found with Kani

## First scenario

We have options:
- filter set to true
- update set to false

🛑 Failed to build!

## Second scenario

We have options:
- filter set to false
- update set to false

🛑 Failed to build!

## Third scenario

We have options:
- filter set to true
- update set to true

🛑 Failed to build

# Now what?

Cargo vendor filterer seems it's not ready to be merged. Thoughts @Firstyear ?

**Comment by uncomfyhalomacro** [comment]
image
I wonder why it fails to do so? is it because of `*-windows-*`? that's weird

**Comment by Firstyear** [comment]
> Cargo vendor filterer seems it's not ready to be merged. Thoughts @Firstyear ?

vendor filter is "nice to have" not required. We have other ways to reduce archive size (like default compression levels etc). 

So I think we opt to skip this for now since it's causing problems, and right now our goal needs to be a "smooth replacement" of the python to rust versions. Throwing in more variables only risks that change.

**Comment by uncomfyhalomacro** [comment]
Yeah I will keep the branch. for now it's dead.

**Pull request closed without merging**
