### PR TITLE
Improve multi crate dl

### PR DESCRIPTION
**Pull request by Firstyear**

### CODE REVIEW

**Comment by Firstyear** [comment]
I think in the case that you have a work space, you don't *need* to specify multiple Cargo.toml/cargo.lock.

The example was home:ngueorguiev:branches:Base:System/s390-tools which doesn't have a workspace at all, but has multiple cargo.toml's within, none of which are also at the root of the sources. 

I tested this change with kanidm and it worked because it has the workspace setup, can you send me the obs repo for wayshot so I can test?

**Comment by uncomfyhalomacro** [comment]
> I think in the case that you have a work space, you don't _need_ to specify multiple Cargo.toml/cargo.lock.
> 
> The example was home:ngueorguiev:branches:Base:System/s390-tools which doesn't have a workspace at all, but has multiple cargo.toml's within, none of which are also at the root of the sources.
> 
> I tested this change with kanidm and it worked because it has the workspace setup, can you send me the obs repo for wayshot so I can test?

Ah i saw the service file between kanidm and wayshot, it seems kanidm just used the root Cargo.toml. I will check with wayshot. it's probably that cargotoml parameter is giving the python script the weird.

here is the OBS project for wayshot https://build.opensuse.org/package/show/X11:Wayland/wayshot

**Comment by uncomfyhalomacro** [comment]
Confirmed that it works after I removed the `cargotoml` parameters. Maybe multi-crate dl should be a separate parameter called `crate`? 

```xml
<services>
  <service name="download_files" mode="manual" />
  <service name="cargo_vendor" mode="manual">
     <param name="srctar">s390-tools.tar.gz</param>
     <param name="compression">zst</param>
     <param name="update">true</param>
     <param name="crate">rust/pvsecret</param>
     <param name="crate">rust/utils</param>
  </service>
  <service name="cargo_audit" mode="manual" />
</services>

**Comment by Firstyear** [comment]
But then it's hard to see when it's multi-manifest with single workspace, vs multi crate. Does wayshot work with single manifest and this PR?

**Comment by uncomfyhalomacro** [comment]
> But then it's hard to see when it's multi-manifest with single workspace, vs multi crate. Does wayshot work with single manifest and this PR?

Yes. It works with a single manifest. But idk why it sometimes does not build correctly after vendored, hence, I decided to add `sync` option.

I will get back to this after things on my side dies down

**Comment by Firstyear** [comment]
Well for now, can we merge this and I'll take a look at wayshot after?

**Pull request merged**
