### PR TITLE
Add experimental vendor_filterer support

### PR DESCRIPTION
**Pull request by msirringhaus**

### CODE REVIEW

**Comment by msirringhaus** [comment]
Build fails because of #76

**Comment by uncomfyhalomacro** [comment]
Hello. As much as I would like to tackle this, I am not sure if the filter still works despite our efforts at https://github.com/openSUSE/obs-service-cargo_vendor/pull/48. Some odd behaviors are described in that PR that is why we didn't pursue this.

**Comment by uncomfyhalomacro** [comment]
> Build fails because of #76

This is now fixed. Please update your branch from upstream changes.

**Comment by msirringhaus** [comment]
Rebased to fix the build.

Regarding testing: I've tried it with cross-platform crates like ripgrep, eza, git-delta, and also with more complicated (and for the most part also cross-platform) crates like zellij, fractal, typst, alacritty, and helix. 
All of them build well (including tests). The only exception I encountered that does not build fine with the filtered vendor-tarball is kanidm. I haven't yet understood exactly what is happening there, but that is the reason I added it as an experimental opt-in flag for now.

**Review by uncomfyhalomacro — APPROVED** [review]
I don't think I have much to comment since all of it is explained well. \cc @Firstyear

**Comment by msirringhaus** [comment]
Oh, and fwiw: HEAD of kanidm works fine, too. But `v1.1.0-rc.16` fails.

**Comment by Firstyear** [comment]
I think that's fine provided we don't need to re-vendor kanidm for now. Worst case I can vendor that manually in the shortterm.

**Review by Firstyear — APPROVED** [review]

**Pull request merged**
